# Generated by Django 5.0.6 on 2024-05-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WTS', 'WTS'), ('WTB', 'WTB')], max_length=3)),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
                ('price', models.CharField(default='ASK', max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
