# Generated by Django 5.0.6 on 2024-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('AED', 'AED'), ('HKD', 'HKD')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Arcade Equipment', 'Arcade Equipment'), ('Audio', 'Audio'), ('Circuit Boards & Components', 'Circuit Boards & Components'), ('Communications', 'Communications'), ('Components', 'Components'), ('Computers', 'Computers'), ('Electronics Accessories', 'Electronics Accessories'), ('GPS Accessories', 'GPS Accessories')], max_length=100),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED'), ('ALL', 'ALL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='type',
            field=models.CharField(choices=[('WTS', 'WTS'), ('WTB', 'WTB'), ('ALL', 'ALL')], max_length=3),
        ),
    ]
