# Generated by Django 5.0.6 on 2024-07-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0002_broadcast_currency_alter_broadcast_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='broadcasting.category'),
        ),
    ]
