# Generated by Django 5.0.6 on 2024-07-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0003_category_alter_broadcast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcasting.category'),
        ),
    ]
