# Generated by Django 5.0.6 on 2024-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0004_alter_broadcast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
