# Generated by Django 5.0.6 on 2024-05-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_companyuser_company_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
