# Generated by Django 5.0.6 on 2024-06-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_profile_verification_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
