# Generated by Django 5.0.6 on 2024-06-20 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=' ', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
